openapi: 3.0.3
info:
  title: ATM Monitoring API
  description: API for monitoring ATM status, transactions, failures, camera logs, and customer statistics.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /atm/monitoring:
    get:
      summary: Get ATM status
      description: Retrieves the current status of the ATM.
      responses:
        '200':
          description: Successful response with ATM status.
          content:
            application/json:
              schema:
                type: string
  /atm/transactions:
    get:
      summary: Get transactions by type
      description: Fetches ATM transactions based on the specified type.
      parameters:
        - name: type
          in: query
          description: Type of transaction (e.g., Deposit, Withdrawal).
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response with transactions.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    type:
                      type: string
                    amount:
                      type: number
  /login:
    post:
      summary: User login
      description: Authenticates the user and returns a JWT token.
      requestBody:
        description: User credentials for authentication.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful login response with JWT token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
  /atm/customers:
    get:
      summary: Get total customers in the last 24 hours
      description: Retrieves the total number of customers served in the last 24 hours.
      responses:
        '200':
          description: Successful response with the total number of customers.
          content:
            application/json:
              schema:
                type: integer
  /atm/failures:
    get:
      summary: Get ATM failures
      description: Retrieves a list of ATM failures, such as downtime and incidents.
      responses:
        '200':
          description: Successful response with a list of failures.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    timestamp:
                      type: string
                      format: date-time
                    description:
                      type: string
  /atm/camera-logs:
    get:
      summary: Process video from ATM cameras
      description: Processes video logs from ATM cameras for a specified time period.
      parameters:
        - name: inputFilePath
          in: query
          description: Path to the input video file.
          required: true
          schema:
            type: string
        - name: outputFilePath
          in: query
          description: Path to the output video file.
          required: true
          schema:
            type: string
        - name: start
          in: query
          description: Start time for processing (e.g., HH:MM:SS).
          required: true
          schema:
            type: string
        - name: end
          in: query
          description: End time for processing (e.g., HH:MM:SS).
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Video processed successfully.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad request due to invalid input.
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal server error during video processing.
          content:
            application/json:
              schema:
                type: string
